### ISSUE TITLE
Backport 1.10.2 EventPriority fix to 1.7.10

### ISSUE THREAD

**Issue by AshIndigo** [MattCzyr/Souls#10]
In the 1.10.2 SoulsEventHandler class the event priority is on LOW while the 1.7.10 version is on HIGH. This breaks the Resolute Ivy from Botania and the Reincarnating enchantment from Extra Utilities. Could you modify the class file to fix this?

**Comment by MattCzyr** [comment]
Fixed in version 1.7.10-1.0.4.
