### ISSUE TITLE
Empty NBT string causing crash when looking at soul entity

### ISSUE THREAD

**Issue by FlaggedBrad** [MattCzyr/Souls#18]
Hi, me and a friend were playing a SP world opened up via LAN. My friend died by a baby skeleton introduced by another mod, and when she pointed her cursor towards the entity, her game crashed. Then, i went out and found her dead soul and crashed as well. [Here's my crash report.](https://puu.sh/vELFe/2be07b4b06.txt) We were playing [the pack "Modern Harmony"](https://www.technicpack.net/modpack/modern-harmony.868567) from the technic launcher. The pack includes "Souls-1.10.2-1.1.2.jar" in the mods folder, and is not up to date. I was wondering if this is patched in version 1.1.3, and if not, can you please fix it? There is a complete list of mods in the crash report, and you can download the pack for yourself if you want to test it.

**Comment by MattCzyr** [comment]
This was indeed fixed in version 1.1.3. Ask the modpack author to update the pack or update Souls manually.
